image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - mkhl.direnv
    - bbenoist.Nix
    - jnoortheen.nix-ide
    - kamadorueda.alejandra
    - rust-lang.rust-analyzer
    - PKief.material-icon-theme
    - tamasfe.even-better-toml
