name: "Build Nix"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Install Cachix
        uses: cachix/cachix-action@v10
        with:
          name: 3waffel
          authToken: "${{secrets.CACHIX_AUTH_TOKEN}}"

      - name: Build Cache
        run: nix develop
